(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else "Unknown actin -- MAKE-ACCOUNT"
                m)))
  (define (call-the-cops amount)
    "Max attempts exceeded!!")
  (define login
    (let ((login-attempts 7))
      (lambda (pw-attempt m)
        (cond ((eq? pw-attempt password)
               (begin (set! login-attempts 7)
                      (dispatch m)))
              ((and (not (eq? pw-attempt password))
                    (<= login-attempts 1))
               call-the-cops)
              (else
                (begin (set! login-attempts (- login-attempts 1))
                       (lambda (amount) "incorrect password")))))))
  login)
