(define rand
  (let ((seed 0))  
    (define (lcg seed)
      (let ((a 1103515245)
            (c 1)
            (m (- (expt 2 31) 1)))
        (remainder (+ (* a seed) c) m)))
    (define (generate)
      (begin (set! seed (lcg seed))
             seed))
    (define (reset new-seed)
      (begin (set! seed new-seed)
             (newline)
             (display "Seed reset!")))
    (define (dispatch msg)
      (cond ((eq? msg 'generate) (generate))
            ((eq? msg 'reset) reset)
            (else 
              (error "No method defined RAND" msg))))
  dispatch))
