(define (make-rand)
  (define seed 0)  
  (define (lcg seed)
    (let ((a 1103515245)
          (c 1)
          (m (- (expt 2 31) 1)))
      (remainder (+ (* a seed) c) m)))
  (define (generate)
    (begin (set! seed (lcg seed))
           seed))
  (define (reset new-seed)
    (set! seed new-seed))
  (define (rand msg)
    (cond ((eq? msg 'generate) (generate))
          ((eq? msg 'reset) reset)
          (else 
            (error "No method defined RAND" msg))))
  rand)

(define rand (make-rand))
