(define (subsets s)
; (newline)
; (display "s: ")
; (display s)
  (if (null? s)
      (list s)
      (let ((rest (subsets (cdr s))))
;       (newline)
;       (display "rest: ")
;       (display rest)
        (append rest (map (lambda (l) (append (list (car s)) l)) 
                          rest)))))
